apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tc-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
    - name: dockerconfig-ws
  params:
    - name: repo-url
    - name: revision
    - name: branch
    - name: app-name
  tasks:
    - name: clone
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
        - name: branch
          value: $(params.branch)
    - name: npminstall
      taskRef:
        name: npminstall
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: tests
      taskRef:
        name: jasmine
      runAfter:
        - npminstall
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: build
      taskRef:
        kind: ClusterTask
        name: buildah
      runAfter:
        - tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
        - name: dockerconfig-ws
          workspace: dockerconfig-ws
      params:
        - name: IMAGE
          value: "us.icr.io/$(context.pipelineRun.namespace)/$(params.app-name)"