apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: juphc-tc-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
    - name: dockerconfig-ws
  params:
    - name: build-image
    - name: repo-url
    - name: branch
      default: main
  tasks:
  
    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: cleanup
        
    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)
      runAfter:
        - init
- name: npminstall
        taskRef:
          name: npm
        runAfter:
          - clone
        workspaces:
          - name: source
            workspace: pipeline-workspace
      - name: tests
        taskRef:
          name: jasmine
        runAfter:
          - npminstall
        workspaces:
          - name: source
            workspace: pipeline-workspace
      - name: build
        taskRef:
          kind: ClusterTask
          name: buildah
        runAfter:
          - tests
        workspaces:
          - name: source
            workspace: pipeline-workspace
          - name: dockerconfig-ws
            workspace: dockerconfig-ws
        params:
          - name: IMAGE
            value: "us.icr.io/$(context.pipelineRun.namespace)/$(params.app-name)"